//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C64Emulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Fullscreen {
            get {
                return ((bool)(this["Fullscreen"]));
            }
            set {
                this["Fullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("806")]
        public int ResolutionWidth {
            get {
                return ((int)(this["ResolutionWidth"]));
            }
            set {
                this["ResolutionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("568")]
        public int ResolutionHeight {
            get {
                return ((int)(this["ResolutionHeight"]));
            }
            set {
                this["ResolutionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Joystick1Map {
            get {
                return ((int)(this["Joystick1Map"]));
            }
            set {
                this["Joystick1Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Joystick2Map {
            get {
                return ((int)(this["Joystick2Map"]));
            }
            set {
                this["Joystick2Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpArrow")]
        public global::SdlDotNet.Input.Key KeySet1Up {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet1Up"]));
            }
            set {
                this["KeySet1Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightArrow")]
        public global::SdlDotNet.Input.Key KeySet1Right {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet1Right"]));
            }
            set {
                this["KeySet1Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DownArrow")]
        public global::SdlDotNet.Input.Key KeySet1Down {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet1Down"]));
            }
            set {
                this["KeySet1Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftArrow")]
        public global::SdlDotNet.Input.Key KeySet1Left {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet1Left"]));
            }
            set {
                this["KeySet1Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftControl")]
        public global::SdlDotNet.Input.Key KeySet1Fire {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet1Fire"]));
            }
            set {
                this["KeySet1Fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keypad8")]
        public global::SdlDotNet.Input.Key KeySet2Up {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet2Up"]));
            }
            set {
                this["KeySet2Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keypad6")]
        public global::SdlDotNet.Input.Key KeySet2Right {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet2Right"]));
            }
            set {
                this["KeySet2Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keypad5")]
        public global::SdlDotNet.Input.Key KeySet2Down {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet2Down"]));
            }
            set {
                this["KeySet2Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keypad4")]
        public global::SdlDotNet.Input.Key KeySet2Left {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet2Left"]));
            }
            set {
                this["KeySet2Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftAlt")]
        public global::SdlDotNet.Input.Key KeySet2Fire {
            get {
                return ((global::SdlDotNet.Input.Key)(this["KeySet2Fire"]));
            }
            set {
                this["KeySet2Fire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastHost {
            get {
                return ((string)(this["LastHost"]));
            }
            set {
                this["LastHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSpeed {
            get {
                return ((bool)(this["ShowSpeed"]));
            }
            set {
                this["ShowSpeed"] = value;
            }
        }
    }
}
